export interface Question {
  id: string;
  category: 'Pattern' | 'Logic' | 'HR' | 'ABAP';
  difficulty: 'Easy' | 'Medium' | 'Hard';
  title: string;
  description: string;
  logic: string;
  hint: string;
  xpFirstSolve: number;
  xpRepeatSolve: number;
  pseudoCode?: string;
  correctAnswer?: string;
}

export const QUESTIONS: Question[] = [
  // ==========================================
  // --- SECTION 1-5 & BONUS LOGIC (1-70) ---
  // ==========================================
  {
    id: 'logic-001',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Print name characters',
    description: 'Print each character of a given name on a new line. Input: ABAP. Output: A\\nB\\nA\\nP',
    logic: 'loop at string/name and write character',
    hint: 'Use a loop (DO string length times) and offset access string+i(1).',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'write'
  },
  {
    id: 'logic-002',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Calculate string length',
    description: 'Calculate string length without using the built-in STRLEN function.',
    logic: 'loop through characters incrementing a counter until end of string',
    hint: 'Loop through characters until you hit empty space or boundary.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'counter'
  },
  {
    id: 'logic-003',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Count vowels in string',
    description: 'Count the number of vowels (A, E, I, O, U) in a given string.',
    logic: 'iterate over characters, check if character matches A, E, I, O, U, and count matches',
    hint: 'Use CO (Contains Only) or CA (Contains Any) or check each character.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'vowel'
  },
  {
    id: 'logic-004',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Count consonants in string',
    description: 'Count the number of consonants in a given string.',
    logic: 'iterate and check if character is a letter but not a vowel',
    hint: 'Check if character matches [a-z] and is not a, e, i, o, u.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'consonant'
  },
  {
    id: 'logic-005',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Count spaces in sentence',
    description: 'Count the number of spaces in a given sentence.',
    logic: 'use FIND ALL OCCURRENCES OF space or loop and check',
    hint: 'Use modern FIND ALL OCCURRENCES or count spaces in a loop.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'space'
  },
  {
    id: 'logic-006',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Lowercase to uppercase conversion',
    description: 'Convert lowercase letters to uppercase without using built-in translation conversion functions.',
    logic: 'convert using ASCII value offset subtraction (e.g., -32)',
    hint: 'Subtract 32 from the ASCII value of lowercase letters.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'ascii'
  },
  {
    id: 'logic-007',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Uppercase to lowercase conversion',
    description: 'Convert uppercase letters to lowercase without using built-in conversion functions.',
    logic: 'convert using ASCII value offset addition (e.g., +32)',
    hint: 'Add 32 to the ASCII value of uppercase letters.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'ascii'
  },
  {
    id: 'logic-008',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Print string in reverse',
    description: 'Print characters of a string in reverse order.',
    logic: 'iterate backwards from length-1 down to 0 and write each character',
    hint: 'Start index from length - 1 and go down to 0.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'reverse'
  },
  {
    id: 'logic-009',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Check string palindrome',
    description: 'Check whether a string is a palindrome. Examples: MADAM -> Palindrome, ABAP -> Not Palindrome',
    logic: 'compare characters from both ends meeting in the middle',
    hint: 'Reverse the string and check if it is equal to the original.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'palindrome'
  },
  {
    id: 'logic-010',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Count character occurrences',
    description: 'Count occurrences of a particular character in a string. E.g. String = SAPABAP, Character = A, Output = 3',
    logic: 'loop over string and increment counter if character matches target',
    hint: 'Compare each character in the string with the target character.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'occurrence'
  },
  {
    id: 'logic-011',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Check even or odd',
    description: 'Check whether a number is even or odd.',
    logic: 'check number mod 2 equals 0',
    hint: 'Use the MOD operator.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'mod'
  },
  {
    id: 'logic-012',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Sum of digits',
    description: 'Find the sum of digits of a number. Example: 1234 -> 10',
    logic: 'sum modulo 10 values while dividing the number by 10',
    hint: 'Extract the last digit using MOD 10, add it, and divide the number by 10.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'digits'
  },
  {
    id: 'logic-013',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Product of digits',
    description: 'Find the product of digits of a number.',
    logic: 'multiply modulo 10 values while dividing the number by 10',
    hint: 'Similar to sum of digits, but multiply instead of add.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'digits'
  },
  {
    id: 'logic-014',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Reverse a number',
    description: 'Reverse a number. Example: 1234 -> 4321',
    logic: 'build reversed number by multiplying previous by 10 and adding mod 10 of current number',
    hint: 'Use MOD 10 and integer division by 10 in a loop.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'reverse'
  },
  {
    id: 'logic-015',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Check palindrome number',
    description: 'Check if a number is a palindrome (e.g. 121 -> Palindrome).',
    logic: 'reverse the number and check if it matches the original',
    hint: 'Reverse the number and compare it to the input.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'palindrome'
  },
  {
    id: 'logic-016',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Check Armstrong number',
    description: 'Check if a number is an Armstrong number (e.g., 153, 370, 371, 407).',
    logic: 'sum of cubes of digits equals the original number',
    hint: 'For each digit, raise to power of count of digits (or cube for 3 digits) and sum them.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'armstrong'
  },
  {
    id: 'logic-017',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Check Prime number',
    description: 'Check whether a number is a Prime number.',
    logic: 'verify if number has no divisors other than 1 and itself',
    hint: 'Loop from 2 to square root of number and check if divisible.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'prime'
  },
  {
    id: 'logic-018',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Print primes up to N',
    description: 'Print all prime numbers between 1 and N.',
    logic: 'loop from 2 to N, check if each number is prime, and write if true',
    hint: 'Use nested loops: outer loop up to N, inner loop to check if prime.',
    xpFirstSolve: 30, xpRepeatSolve: 6,
    correctAnswer: 'prime'
  },
  {
    id: 'logic-019',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Find factorial using loops',
    description: 'Find factorial of a number using loops.',
    logic: 'multiply integers from 1 up to N',
    hint: 'Use a DO or WHILE loop to multiply numbers.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'factorial'
  },
  {
    id: 'logic-020',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Generate Fibonacci series',
    description: 'Generate Fibonacci series up to N elements (e.g. 0 1 1 2 3 5 8 13).',
    logic: 'print next number as sum of previous two numbers',
    hint: 'Initialize two variables as 0 and 1, print them, then sum and shift in loop.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'fibonacci'
  },
  {
    id: 'logic-021',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Pattern: Right Triangle',
    description: 'Print right triangle pattern of stars:\n*\n* *\n* * *\n* * * *\n* * * * *',
    logic: 'outer loop for rows, inner loop prints star * count equal to current row index',
    hint: 'Outer loop from 1 to N, inner loop from 1 to outer loop index.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'triangle'
  },
  {
    id: 'logic-022',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Pattern: Inverted Triangle',
    description: 'Print inverted triangle pattern:\n* * * * *\n* * * *\n* * *\n* *\n*',
    logic: 'loop downwards from N to 1, print stars equal to index',
    hint: 'Outer loop goes downwards from N to 1.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'inverted'
  },
  {
    id: 'logic-023',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Pattern: Number Triangle',
    description: 'Print number triangle:\n1\n1 2\n1 2 3\n1 2 3 4',
    logic: 'outer loop for rows, inner loop prints numbers from 1 to row index',
    hint: 'Print the inner loop counter inside the inner loop.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'number'
  },
  {
    id: 'logic-024',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Pattern: Reverse Number Triangle',
    description: 'Print reverse number triangle:\n1 2 3 4 5\n1 2 3 4\n1 2 3\n1 2\n1',
    logic: 'outer loop from N down to 1, inner loop prints from 1 to outer index',
    hint: 'Decrement the outer loop and print numbers up to it.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'reverse'
  },
  {
    id: 'logic-025',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Pattern: Continuous Number Pattern',
    description: 'Print continuous number pattern:\n1\n2 3\n4 5 6\n7 8 9 10',
    logic: 'maintain a global counter, increment and print inside row loops',
    hint: 'Increment a separate counter in each inner iteration and print it.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'counter'
  },
  {
    id: 'logic-026',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Pattern: Square pattern',
    description: 'Print square pattern:\n* * * *\n* * * *\n* * * *\n* * * *',
    logic: 'loop N times, each row print N stars',
    hint: 'Two nested loops from 1 to N, writing a star each time.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'square'
  },
  {
    id: 'logic-027',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Pattern: Hollow square',
    description: 'Print hollow square pattern.',
    logic: 'print stars only on border coordinates (first/last row or column)',
    hint: 'Print star if row=1, row=N, col=1 or col=N. Else print space.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'hollow'
  },
  {
    id: 'logic-028',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Pattern: Pyramid',
    description: 'Print centered star pyramid.',
    logic: 'print spaces from N-row down to 1, then print 2*row-1 stars',
    hint: 'Output spaces first, then stars. Star count increases by 2 per row.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'pyramid'
  },
  {
    id: 'logic-029',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Pattern: Inverted pyramid',
    description: 'Print inverted centered pyramid.',
    logic: 'print spaces equal to row, then print 2*(N-row)-1 stars',
    hint: 'Reverse of the normal pyramid: print increasing spaces and decreasing stars.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'inverted'
  },
  {
    id: 'logic-030',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Pattern: Diamond pattern',
    description: 'Print diamond pattern.',
    logic: 'print normal pyramid, then inverted pyramid',
    hint: 'Combine a normal pyramid and an inverted pyramid in sequence.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'diamond'
  },
  {
    id: 'logic-031',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Count words in sentence',
    description: 'Count words in a sentence.',
    logic: 'split string by spaces and count resulting segments',
    hint: 'Split by space and count the size of the resulting array/table.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'words'
  },
  {
    id: 'logic-032',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Reverse each word separately',
    description: 'Reverse each word separately. Input: SAP ABAP. Output: PAS PABA',
    logic: 'split into words, reverse each word, and concatenate back',
    hint: 'Split sentence into internal table, loop, reverse each line, concatenate.',
    xpFirstSolve: 30, xpRepeatSolve: 6,
    correctAnswer: 'reverse'
  },
  {
    id: 'logic-033',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find duplicate characters',
    description: 'Find duplicate characters. Input: PROGRAMMING. Output: R M G',
    logic: 'keep track of character counts and output characters with count > 1',
    hint: 'Use a tracking map or count character occurrences.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'duplicate'
  },
  {
    id: 'logic-034',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'First non-repeating character',
    description: 'Find first non-repeating character in a string.',
    logic: 'count frequency, then find first character with frequency = 1',
    hint: 'Scan characters, store counts, and find the first character with count 1.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'non-repeating'
  },
  {
    id: 'logic-035',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Remove duplicate characters',
    description: 'Remove duplicate characters. Input: AABBCDD. Output: ABCD',
    logic: 'build new string by adding characters that are not already present',
    hint: 'Use a unique tracker to only add unseen characters.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'duplicate'
  },
  {
    id: 'logic-036',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Check anagram strings',
    description: 'Check whether two strings are anagrams. E.g. LISTEN and SILENT',
    logic: 'sort both strings and compare if equal',
    hint: 'Sort the letters of both words and check if they match exactly.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'anagram'
  },
  {
    id: 'logic-037',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Count frequency of each character',
    description: 'Count frequency of each character. Input: ABAP. Output: A = 2, B = 1, P = 1',
    logic: 'use map/table to store and print char counts',
    hint: 'Collect characters into a key-value or sorted structure and print counts.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'frequency'
  },
  {
    id: 'logic-038',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find longest word in sentence',
    description: 'Find longest word in a sentence.',
    logic: 'split by space and find word with maximum length',
    hint: 'Keep track of max length and corresponding word while iterating.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'longest'
  },
  {
    id: 'logic-039',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Replace vowels with *',
    description: 'Replace all vowels in a string with *. Example: ABAP -> *B*P',
    logic: 'replace occurrences of A, E, I, O, U with *',
    hint: 'Use REPLACE ALL OCCURRENCES OF with regex [aeiouAEIOU] or iterate.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'replace'
  },
  {
    id: 'logic-040',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Check only digits',
    description: 'Check whether a string contains only digits.',
    logic: 'verify if all characters match digits 0-9',
    hint: 'Use CO (Contains Only) with "0123456789" or regex match.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'digits'
  },
  {
    id: 'logic-041',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Create & print internal table 1-10',
    description: 'Create an internal table with numbers 1–10 and print all entries.',
    logic: 'append 1 to 10 in loop, loop at and write',
    hint: 'Use a simple DO loop with APPEND, and LOOP AT to print.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'append'
  },
  {
    id: 'logic-042',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Max value from internal table',
    description: 'Find maximum value from internal table.',
    logic: 'loop and update max variable if current > max',
    hint: 'Sort descending and read index 1, or loop tracking the highest value.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'maximum'
  },
  {
    id: 'logic-043',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Min value from internal table',
    description: 'Find minimum value from internal table.',
    logic: 'loop and update min variable if current < min',
    hint: 'Sort ascending and read index 1, or loop tracking the lowest value.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'minimum'
  },
  {
    id: 'logic-044',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Sum of internal table entries',
    description: 'Calculate sum of all entries in internal table.',
    logic: 'loop and add each entry to accumulator variable',
    hint: 'Use a loop to add the values of each row to a sum variable.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'sum'
  },
  {
    id: 'logic-045',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Average of internal table values',
    description: 'Calculate average of values in internal table.',
    logic: 'divide sum of entries by line count',
    hint: 'Calculate sum, get table lines using lines(lt_table), and divide.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'average'
  },
  {
    id: 'logic-046',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Remove duplicate records from itab',
    description: 'Remove duplicate records from internal table.',
    logic: 'use DELETE ADJACENT DUPLICATES',
    hint: 'Sort the table first, then use DELETE ADJACENT DUPLICATES FROM.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'delete adjacent'
  },
  {
    id: 'logic-047',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Sort internal table ascending',
    description: 'Sort internal table in ascending order.',
    logic: 'use SORT statement',
    hint: 'Use SORT lt_table ASCENDING.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'sort'
  },
  {
    id: 'logic-048',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Sort internal table descending',
    description: 'Sort internal table in descending order.',
    logic: 'use SORT statement with DESCENDING addition',
    hint: 'Use SORT lt_table DESCENDING.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'sort'
  },
  {
    id: 'logic-049',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Second highest number in itab',
    description: 'Find second highest number from internal table. Example: 10 30 20 50 40 -> Output = 40',
    logic: 'sort descending, delete duplicates, read index 2',
    hint: 'Sort table descending, remove adjacent duplicates, and read the 2nd row.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'index 2'
  },
  {
    id: 'logic-050',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Separate even and odd numbers',
    description: 'Separate even and odd numbers into two different internal tables.',
    logic: 'loop, check mod 2, append to respective even or odd table',
    hint: 'Loop through source table, check if MOD 2 = 0, append to target tables.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'even'
  },
  {
    id: 'logic-051',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find GCD of two numbers',
    description: 'Find Greatest Common Divisor (GCD) of two numbers.',
    logic: 'use Euclidean algorithm, modulo repeatedly until remainder is 0',
    hint: 'Use a loop replacing (A, B) with (B, A MOD B) until B becomes 0.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'gcd'
  },
  {
    id: 'logic-052',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find LCM of two numbers',
    description: 'Find Least Common Multiple (LCM) of two numbers.',
    logic: 'lcm = (a * b) / gcd(a, b)',
    hint: 'Multiply the numbers and divide by their Greatest Common Divisor.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'lcm'
  },
  {
    id: 'logic-053',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Swap numbers without third variable',
    description: 'Swap two numbers without using a third temporary variable.',
    logic: 'a = a + b, b = a - b, a = a - b',
    hint: 'Add both numbers, then subtract to isolate each value.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'swap'
  },
  {
    id: 'logic-054',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Find largest among three numbers',
    description: 'Find the largest among three numbers.',
    logic: 'compare A, B, and C using IF checks',
    hint: 'Use nested IF or compound conditions (A > B AND A > C).',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'largest'
  },
  {
    id: 'logic-055',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Find smallest among three numbers',
    description: 'Find the smallest among three numbers.',
    logic: 'compare A, B, and C using IF checks',
    hint: 'Use nested IF or compound conditions (A < B AND A < C).',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'smallest'
  },
  {
    id: 'logic-056',
    category: 'Logic',
    difficulty: 'Easy',
    title: 'Print multiplication table',
    description: 'Print multiplication table of a given number.',
    logic: 'loop from 1 to 10, write multiplier and product',
    hint: 'Use DO 10 times, multiply index by the input number.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'multiplication'
  },
  {
    id: 'logic-057',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Print tables from 1 to 10',
    description: 'Print multiplication tables from 1 to 10.',
    logic: 'nested loops: outer 1-10, inner 1-10',
    hint: 'Use a nested loop structure to print tables for numbers 1 through 10.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'nested'
  },
  {
    id: 'logic-058',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find missing number in sequence',
    description: 'Find missing number in sequence from 1 to N.',
    logic: 'expected sum = n*(n+1)/2, actual sum is sum of array; missing = expected - actual',
    hint: 'Calculate sum of numbers 1 to N, subtract actual sum of table entries.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'missing'
  },
  {
    id: 'logic-059',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Check perfect number',
    description: 'Check perfect number. Example: 6 = 1+2+3.',
    logic: 'sum proper divisors and check if sum equals number',
    hint: 'Find all divisors of number up to N/2 and sum them up.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'perfect'
  },
  {
    id: 'logic-060',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Print Pascal Triangle',
    description: 'Print Pascal Triangle up to N rows.',
    logic: 'calculate binomial coefficients using C(n, k) = C(n-1, k-1) + C(n-1, k)',
    hint: 'Each number is the sum of the two directly above it.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'pascal'
  },
  {
    id: 'logic-061',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Bubble Sort implementation',
    description: 'Bubble Sort implementation.',
    logic: 'loop over array, compare adjacent elements, swap if out of order',
    hint: 'Use nested loops, swapping elements if list[j] > list[j+1].',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'bubble sort'
  },
  {
    id: 'logic-062',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Selection Sort implementation',
    description: 'Selection Sort implementation.',
    logic: 'find minimum element, swap with first unsorted element',
    hint: 'Keep track of minimum in remaining unsorted portion and swap it.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'selection sort'
  },
  {
    id: 'logic-063',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Linear Search implementation',
    description: 'Linear Search implementation.',
    logic: 'loop over array, return index if element matches target',
    hint: 'Iterate through all items sequentially to find the target value.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'linear search'
  },
  {
    id: 'logic-064',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Binary Search implementation',
    description: 'Binary Search implementation.',
    logic: 'binary search: divide and conquer in sorted array',
    hint: 'Maintain low and high pointers, examine midpoint, adjust bounds.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'binary search'
  },
  {
    id: 'logic-065',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Count duplicate numbers in itab',
    description: 'Count duplicate numbers in internal table.',
    logic: 'collect counts and sum rows with count > 1',
    hint: 'Count frequencies and accumulate rows occurring more than once.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'duplicate'
  },
  {
    id: 'logic-066',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Merge two internal tables',
    description: 'Merge two internal tables.',
    logic: 'append lines of one table to another or use VALUE with BASE',
    hint: 'Use APPEND LINES OF lt_tab2 TO lt_tab1 or VALUE operator.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'merge'
  },
  {
    id: 'logic-067',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find common elements in two itabs',
    description: 'Find common elements between two internal tables.',
    logic: 'loop at table 1, read table 2, append to results if found',
    hint: 'LOOP AT the first table and do a READ TABLE or use a loop check.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'common'
  },
  {
    id: 'logic-068',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Find unique elements in itabs',
    description: 'Find unique elements from combined tables.',
    logic: 'merge tables, sort, delete duplicates',
    hint: 'Merge tables and eliminate duplicates to get unique entries.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'unique'
  },
  {
    id: 'logic-069',
    category: 'Logic',
    difficulty: 'Hard',
    title: 'Transpose a matrix',
    description: 'Transpose a matrix (flip rows to columns).',
    logic: 'transpose: result[col][row] = input[row][col]',
    hint: 'Loop through row indices, inner loop through columns, assign to swapped target.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'transpose'
  },
  {
    id: 'logic-070',
    category: 'Logic',
    difficulty: 'Medium',
    title: 'Simple calculator using CASE',
    description: 'Create a simple menu-driven calculator using CASE.',
    logic: 'case input_operator. when "+". ... when "-". ... endcase.',
    hint: 'Use CASE statements to branch logic based on +, -, *, or /.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'case'
  },

  // ==========================================
  // --- ABAP & RAP THEORY PHASES (1-10) ---
  // ==========================================
  {
    id: 'abap-001',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is SAP?',
    description: 'Explain what SAP stands for and its core purpose as an enterprise system.',
    logic: 'Systems Applications and Products in Data Processing, ERP package',
    hint: 'SAP is a multinational software corporation and stands for Systems, Applications, and Products.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'Systems Applications and Products'
  },
  {
    id: 'abap-002',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is ERP?',
    description: 'Explain the concept of ERP (Enterprise Resource Planning).',
    logic: 'Enterprise Resource Planning software for integrated business processes',
    hint: 'Integrates core business processes (finance, HR, manufacturing, supply chain) into a single system.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'Enterprise Resource Planning'
  },
  {
    id: 'abap-003',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Difference between SAP and ABAP',
    description: 'Contrast SAP (the product) with ABAP (the programming language).',
    logic: 'SAP is the ERP software suite, while ABAP is the language used to write/customize it',
    hint: 'One is the system, the other is the proprietary language developed by SAP.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'programming language'
  },
  {
    id: 'abap-004',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are SAP modules?',
    description: 'Name key functional and technical modules of SAP.',
    logic: 'MM, FI, CO, SD, PP, HR functional modules; ABAP, BASIS technical modules',
    hint: 'Think of modules like MM (Materials Management), FI (Financial Accounting), and SD (Sales & Distribution).',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'modules'
  },
  {
    id: 'abap-005',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is SAP architecture?',
    description: 'Describe the high-level architecture of SAP R/3 or NetWeaver systems.',
    logic: 'SAP architecture consists of layers linking database, application, and presentation server',
    hint: 'Discuss presentation, application, and database servers.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'layers'
  },
  {
    id: 'abap-006',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Explain 3-tier architecture in SAP',
    description: 'Identify and explain the three layers in SAP 3-tier architecture.',
    logic: 'Presentation Layer (GUI), Application Layer (ABAP engine), Database Layer',
    hint: 'Presentation, Application, and Database tiers.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'Presentation'
  },
  {
    id: 'abap-007',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is client in SAP?',
    description: 'Explain client-specific data and the purpose of a Client ID in SAP.',
    logic: 'a client is a self-contained unit with separate master data and tables',
    hint: 'It is a 3-digit code partition. Cust-specific data is kept separate.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'self-contained'
  },
  {
    id: 'abap-008',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is transaction code (T-code)?',
    description: 'Define T-codes and explain their usage in SAP.',
    logic: 'shortcut key to launch specific applications, screens, or reports',
    hint: 'E.g., SE38 for ABAP editor, SE11 for Data Dictionary.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'shortcut'
  },
  {
    id: 'abap-009',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is ABAP Workbench?',
    description: 'Explain the tools contained within the ABAP Workbench.',
    logic: 'set of tools to write code, design screens, and edit dictionary elements (SE80)',
    hint: 'Accessed via SE80, it integrates SE38, SE11, SE37, etc.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'tools'
  },
  {
    id: 'abap-010',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Difference between SE38 and SE80',
    description: 'Compare the single-program editor (SE38) with the Object Navigator (SE80).',
    logic: 'SE38 is for ABAP editor (only reports/programs), SE80 is Object Navigator for full package structures',
    hint: 'SE80 contains packages, classes, views, and lets you browse everything.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'SE80'
  },
  {
    id: 'abap-011',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are data types in ABAP?',
    description: 'List predefined data types in ABAP (character, numeric, etc.).',
    logic: 'C (Character), I (Integer), D (Date), T (Time), P (Packed decimal), N (Numeric text)',
    hint: 'Standard ABAP elementary types: C, N, D, T, I, F, P, X.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'types'
  },
  {
    id: 'abap-012',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Difference between TYPE and LIKE',
    description: 'Differentiate between the TYPE and LIKE operators in ABAP declarations.',
    logic: 'TYPE references a data type, LIKE references an existing data object',
    hint: 'TYPE references a blueprint; LIKE references an already declared variable.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'LIKE'
  },
  {
    id: 'abap-013',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are constants?',
    description: 'How do you declare constants in ABAP, and why are they used?',
    logic: 'declared using CONSTANTS statement, value cannot be changed during execution',
    hint: 'Use CONSTANTS key VALUE val.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'CONSTANTS'
  },
  {
    id: 'abap-014',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Difference between CHECK, CONTINUE, EXIT',
    description: 'Contrast CHECK, CONTINUE, and EXIT statements inside loops.',
    logic: 'CHECK checks condition; CONTINUE skips to next iteration; EXIT leaves loop',
    hint: 'CONTINUE skips rest of current loop iteration; EXIT terminates loop entirely.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'loop'
  },
  {
    id: 'abap-015',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Difference between DO, WHILE, LOOP',
    description: 'Explain when DO, WHILE, and LOOP AT are used in ABAP.',
    logic: 'DO runs N times; WHILE runs as long as condition holds; LOOP AT iterates over internal tables',
    hint: 'LOOP AT requires an internal table.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'iteration'
  },
  {
    id: 'abap-016',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is an internal table?',
    description: 'Explain what an internal table represents in ABAP.',
    logic: 'temporary memory structure used to hold database records dynamically',
    hint: 'It exists in-memory during execution to process multi-row data.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'memory'
  },
  {
    id: 'abap-017',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference: internal table vs work area',
    description: 'Differentiate between an internal table and a work area.',
    logic: 'internal table holds multiple rows, work area holds only one row',
    hint: 'Think of internal table as a spreadsheet and work area as a single row.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'row'
  },
  {
    id: 'abap-018',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of internal tables',
    description: 'Identify the three types of internal tables in ABAP.',
    logic: 'Standard key tables, Sorted tables, Hashed tables',
    hint: 'Standard, Sorted, and Hashed.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Hashed'
  },
  {
    id: 'abap-019',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Standard, Sorted, and Hashed table difference',
    description: 'Contrast Standard, Sorted, and Hashed tables based on access and index availability.',
    logic: 'Standard allows index access; Sorted is kept sorted; Hashed allows O(1) key access',
    hint: 'Standard is linear, Sorted uses binary search, Hashed uses hashing algorithm.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'O(1)'
  },
  {
    id: 'abap-020',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is field-symbol?',
    description: 'Explain field-symbols and their performance advantages in ABAP.',
    logic: 'a placeholder/pointer that references table rows directly in memory',
    hint: 'Avoids overhead of copying data into work areas (ASSIGNING field-symbol).',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'pointer'
  },
  {
    id: 'abap-021',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference between APPEND and COLLECT',
    description: 'Contrast APPEND and COLLECT statements in ABAP.',
    logic: 'APPEND adds row to end; COLLECT aggregates/sums numeric values based on unique keys',
    hint: 'COLLECT is used for summing up values by key during insertion.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'COLLECT'
  },
  {
    id: 'abap-022',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference between READ TABLE and LOOP AT',
    description: 'Compare READ TABLE and LOOP AT in terms of target row counts.',
    logic: 'READ TABLE reads single row; LOOP AT iterates over multiple rows',
    hint: 'READ TABLE extracts first match. LOOP AT runs code for all matching rows.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'LOOP AT'
  },
  {
    id: 'abap-023',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is sy-subrc?',
    description: 'Explain the purpose and common return values of system variable sy-subrc.',
    logic: 'return code of statement (0 means success, 4 means not found)',
    hint: 'If sy-subrc = 0, the operation completed successfully.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'success'
  },
  {
    id: 'abap-024',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference between MODIFY and UPDATE',
    description: 'Differentiate between MODIFY and UPDATE in Open SQL.',
    logic: 'UPDATE edits existing rows; MODIFY inserts or updates depending on primary key match',
    hint: 'MODIFY works as an upsert (update if exists, else insert).',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'upsert'
  },
  {
    id: 'abap-025',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is OCCURS 0?',
    description: 'Explain the obsolete OCCURS 0 clause in old internal table declarations.',
    logic: 'obsolete syntax to define table with header line, allocating memory dynamically',
    hint: 'Replaced by TYPE STANDARD TABLE OF in modern ABAP.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'obsolete'
  },
  {
    id: 'abap-026',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is header line?',
    description: 'Explain internal tables with header lines and why they are deprecated.',
    logic: 'internal table sharing name with its work area, causing scope confusion',
    hint: 'It acts as both table and structure. Deprecated in classes.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'deprecated'
  },
  {
    id: 'abap-027',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference: CLEAR, REFRESH, FREE',
    description: 'Differentiate CLEAR, REFRESH, and FREE in memory management.',
    logic: 'CLEAR clears work area/header line; REFRESH empties table rows; FREE releases table memory',
    hint: 'FREE completely releases memory back to system.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'memory'
  },
  {
    id: 'abap-028',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is binary search?',
    description: 'Explain how BINARY SEARCH operates on internal tables.',
    logic: 'search technique dividing sorted interval in half, reducing complexity to O(log N)',
    hint: 'Table MUST be sorted before calling READ TABLE ... BINARY SEARCH.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'sorted'
  },
  {
    id: 'abap-029',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Why sorted table faster than standard?',
    description: 'Explain sorted tables performance search advantage.',
    logic: 'sorted tables use binary search (O(log N)) instead of linear scan (O(N))',
    hint: 'Think about algorithmic search complexity.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'O(log N)'
  },
  {
    id: 'abap-030',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'When should hashed tables be used?',
    description: 'State the ideal scenario to use a Hashed internal table.',
    logic: 'large tables where rows are accessed repeatedly by unique key (O(1) complexity)',
    hint: 'Hashing key access is independent of table size.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'O(1)'
  },
  {
    id: 'abap-031',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is DDIC?',
    description: 'Define SAP Data Dictionary (SE11) and its function.',
    logic: 'central database management and metadata editor in SAP',
    hint: 'It allows creation of tables, structures, views, domains, and helps ensure data integrity.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'metadata'
  },
  {
    id: 'abap-032',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference between Domain and Data Element',
    description: 'Contrast technical (Domain) and semantic (Data Element) definitions.',
    logic: 'Domain defines data type and length; Data Element defines semantic label and description',
    hint: 'One domain can be reused in multiple data elements.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'semantic'
  },
  {
    id: 'abap-033',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is metadata?',
    description: 'Explain metadata in DDIC context.',
    logic: 'data about data, describing table schemas, relationships, and constraints',
    hint: 'DDIC objects define table structures, types, and labels in the database.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'definition'
  },
  {
    id: 'abap-034',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of tables in SAP',
    description: 'Identify the three types of database tables in DDIC.',
    logic: 'Transparent tables, Pooled tables, Cluster tables',
    hint: 'Transparent, pooled, and cluster tables.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Cluster'
  },
  {
    id: 'abap-035',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Transparent, Pooled, and Cluster table difference',
    description: 'Differentiate the physical structures of Transparent, Pooled, and Cluster tables.',
    logic: 'Transparent table maps 1:1 on DB; Pooled/Cluster tables store many SAP tables inside one physical database table',
    hint: 'Transparent table has the same name and structure in SAP and physical database.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: '1:1'
  },
  {
    id: 'abap-036',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is a view?',
    description: 'Explain database view in DDIC.',
    logic: 'virtual table projecting data from one or more physical tables',
    hint: 'Simplifies queries by representing joined tables as a single object.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'virtual'
  },
  {
    id: 'abap-037',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of views',
    description: 'List the four standard DDIC view types.',
    logic: 'Database View, Projection View, Maintenance View, Help View',
    hint: 'Maintenance and Help views are popular SAP-specific view types.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Maintenance'
  },
  {
    id: 'abap-038',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is search help?',
    description: 'Explain what search help (F4 help) represents.',
    logic: 'input help utility providing list of values for fields',
    hint: 'Provides the F4 dropdown list of available entries in a field.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'F4'
  },
  {
    id: 'abap-039',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of search help',
    description: 'Identify the two types of search help.',
    logic: 'Elementary Search Help, Collective Search Help',
    hint: 'Collective search help groups multiple elementary search helps together.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Collective'
  },
  {
    id: 'abap-040',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is lock object?',
    description: 'Explain lock objects and enqueue/dequeue concepts in SAP.',
    logic: 'synchronization mechanism to prevent concurrent writes (ENQUEUE and DEQUEUE function modules)',
    hint: 'Starts with EY or EZ. Used to lock rows for modification.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'ENQUEUE'
  },
  {
    id: 'abap-041',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are technical settings?',
    description: 'Explain technical settings in table definition.',
    logic: 'defines class, size category, and buffering parameters',
    hint: 'Determines how the table is stored and whether it is buffered.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'size'
  },
  {
    id: 'abap-042',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is buffering?',
    description: 'Explain table buffering in SAP.',
    logic: 'caching table data in application layer memory to speed up reads',
    hint: 'Reduces database load by storing lookup data in NetWeaver memory.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'cache'
  },
  {
    id: 'abap-043',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Primary key vs Foreign key',
    description: 'Differentiate between primary keys and foreign keys in database design.',
    logic: 'primary key uniquely identifies a row; foreign key defines relationships between tables',
    hint: 'Foreign key is used to define value constraints and linkages.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'relationships'
  },
  {
    id: 'abap-044',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is append structure?',
    description: 'Define append structures and their usage.',
    logic: 'custom structure appended to standard tables/structures without modifying core code',
    hint: 'Allows adding custom customer fields to standard SAP structures safely.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'custom structure'
  },
  {
    id: 'abap-045',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is TMG (Table Maintenance Generator)?',
    description: 'Explain Table Maintenance Generator (TMG) and transaction SM30.',
    logic: 'utility tool generating screens to maintain/edit table entries via SM30',
    hint: 'Used to build data entry screens automatically for custom tables.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'SM30'
  },
  {
    id: 'abap-046',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is a report in ABAP?',
    description: 'Define reports in the ABAP workbench.',
    logic: 'ABAP program displaying formatted output based on user inputs',
    hint: 'Starts with the REPORT statement and displays data.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'program'
  },
  {
    id: 'abap-047',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Types of reports',
    description: 'Identify report architectures in SAP ABAP.',
    logic: 'Classical Reports, Interactive Reports, ALV Reports',
    hint: 'Three main report types (ALV is modern grid-based).',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'ALV'
  },
  {
    id: 'abap-048',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Explain classical report',
    description: 'State the layout and behavior of classical reports.',
    logic: 'single screen list report with linear flow, not supporting secondary lists',
    hint: 'Outputs sequential lines via WRITE statement.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'single'
  },
  {
    id: 'abap-049',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are report events?',
    description: 'List the chronological events that fire during report execution.',
    logic: 'INITIALIZATION, START-OF-SELECTION, END-OF-SELECTION, TOP-OF-PAGE, END-OF-PAGE',
    hint: 'INITIALIZATION occurs before selection screen. START-OF-SELECTION pulls data.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'INITIALIZATION'
  },
  {
    id: 'abap-050',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is START-OF-SELECTION?',
    description: 'Explain the START-OF-SELECTION event.',
    logic: 'default event where main database query and data selection occur',
    hint: 'Runs immediately after the selection screen input validation.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'default'
  },
  {
    id: 'abap-051',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is INITIALIZATION?',
    description: 'Explain when the INITIALIZATION event is used.',
    logic: 'event to set default parameters on the selection screen before display',
    hint: 'Ideal for pre-populating dates or checkboxes.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'default'
  },
  {
    id: 'abap-052',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is TOP-OF-PAGE?',
    description: 'Explain the purpose of the TOP-OF-PAGE event.',
    logic: 'displays headers or title lines at top of printed list reports',
    hint: 'Triggered when the first WRITE statement is executed or page wraps.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'headers'
  },
  {
    id: 'abap-053',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is HIDE statement?',
    description: 'Explain the HIDE statement in classical list reporting.',
    logic: 'stores key values of current line to use in detail lists (interactive lists)',
    hint: 'Pushes row keys to a system buffer linked to the current line.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'buffer'
  },
  {
    id: 'abap-054',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is interactive report?',
    description: 'Explain how interactive reports differ from classical reports.',
    logic: 'allows user to double-click on lines to open secondary lists with details',
    hint: 'Supports up to 20 secondary lists triggered by interactive events.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'secondary'
  },
  {
    id: 'abap-055',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Classical vs Interactive report difference',
    description: 'State the difference between Classical and Interactive report types.',
    logic: 'Classical is static list, Interactive allows drilling down via double click',
    hint: 'Drill-down capacity is key difference.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'static'
  },
  {
    id: 'abap-056',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is AT LINE-SELECTION?',
    description: 'Explain the AT LINE-SELECTION event.',
    logic: 'event triggered when user double-clicks a row on a classical list',
    hint: 'Launches a secondary list based on double click action.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'double-click'
  },
  {
    id: 'abap-057',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is sy-lsind?',
    description: 'Explain the system variable sy-lsind.',
    logic: 'index of current list level in interactive list (0 = basic, 1 = first detail)',
    hint: 'Determines the level of the active drill-down list.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'index'
  },
  {
    id: 'abap-058',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is ALV?',
    description: 'Explain ABAP List Viewer (ALV).',
    logic: 'grid control providing advanced sorting, filtering, and export capabilities out of the box',
    hint: 'Provides tabular UI grid control with built-in standard functionality.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'grid'
  },
  {
    id: 'abap-059',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Advantages of ALV',
    description: 'Why is ALV preferred over writing classical output reports?',
    logic: 'provides built-in sorting, filtering, columns configuration, Excel export',
    hint: 'Saves developer time by offering pre-built table manipulation features.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'sorting'
  },
  {
    id: 'abap-060',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of ALV',
    description: 'Identify different types of ALV formats in SAP.',
    logic: 'List ALV, Grid ALV, Block ALV, Hierarchical ALV',
    hint: 'Grid uses CL_GUI_ALV_GRID; List is simpler; Block groups sections.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Grid'
  },
  {
    id: 'abap-061',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is selection screen?',
    description: 'Explain selection screen and its purpose.',
    logic: 'interface to input selection criteria before program run',
    hint: 'Built using PARAMETERS and SELECT-OPTIONS declarations.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'criteria'
  },
  {
    id: 'abap-062',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'PARAMETERS vs SELECT-OPTIONS',
    description: 'Contrast PARAMETERS and SELECT-OPTIONS in ABAP selection screens.',
    logic: 'PARAMETERS is single input; SELECT-OPTIONS is a range table (SIGN, OPTION, LOW, HIGH)',
    hint: 'SELECT-OPTIONS has a low-high range and creates an internal range table structure.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'range'
  },
  {
    id: 'abap-063',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is NO-DISPLAY?',
    description: 'Explain NO-DISPLAY addition in parameter definitions.',
    logic: 'hides the parameter from selection screen but retains it in program logic',
    hint: 'Hides parameters that might be populated dynamically or via SUBMIT.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'hides'
  },
  {
    id: 'abap-064',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is obligatory field?',
    description: 'Explain OBLIGATORY clause in parameter declarations.',
    logic: 'makes input field mandatory on selection screen',
    hint: 'Similar to required/not null inputs in standard forms.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'mandatory'
  },
  {
    id: 'abap-065',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'How to validate selection screen?',
    description: 'Explain how and where inputs are validated before execution.',
    logic: 'validate in AT SELECTION-SCREEN event and throw error message if invalid',
    hint: 'Use MESSAGE ... TYPE \'E\' in AT SELECTION-SCREEN block.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'SELECTION-SCREEN'
  },
  {
    id: 'abap-066',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is AT SELECTION-SCREEN?',
    description: 'Explain the purpose of the AT SELECTION-SCREEN event.',
    logic: 'event handling input verification and dynamic formatting of selection screen',
    hint: 'Triggered when the user presses Enter or Execute on selection screen.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'input'
  },
  {
    id: 'abap-067',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are radio buttons?',
    description: 'Explain radio buttons declaration on selection screens.',
    logic: 'grouped input elements allowing selection of only one option (RADIOBUTTON GROUP)',
    hint: 'Grouped parameters where only one can be checked (value \'X\').',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'GROUP'
  },
  {
    id: 'abap-068',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are checkboxes?',
    description: 'Explain checkbox parameter handling.',
    logic: 'boolean parameter that can be checked (value \'X\') or unchecked (value space)',
    hint: 'Declared using PARAMETERS ... AS CHECKBOX.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'CHECKBOX'
  },
  {
    id: 'abap-069',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are blocks and frames?',
    description: 'Explain how to group elements on selection screens.',
    logic: 'SELECTION-SCREEN BEGIN OF BLOCK ... WITH FRAME TITLE ...',
    hint: 'Draws a border frame and title header around selection screen fields.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'BLOCK'
  },
  {
    id: 'abap-070',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'SELECT-OPTIONS vs RANGES',
    description: 'Contrast SELECT-OPTIONS and RANGES in ABAP.',
    logic: 'SELECT-OPTIONS generates visual input; RANGES creates identical memory structure without screen elements',
    hint: 'RANGES is declared programmatically to create range tables.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'range'
  },
  {
    id: 'abap-071',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is modularization?',
    description: 'Explain modularization and code layout partitioning.',
    logic: 'breaking code into independent reusable blocks (includes, subroutines, modules)',
    hint: 'Aims to reduce duplicate code and improve maintenance.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'reusable'
  },
  {
    id: 'abap-072',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Advantages of modularization',
    description: 'State the benefits of modularizing code.',
    logic: 'reusability, clean structure, easy debugging, testability',
    hint: 'Helps in writing DRY (Don\'t Repeat Yourself) code.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'structure'
  },
  {
    id: 'abap-073',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is INCLUDE program?',
    description: 'Explain INCLUDE programs and their limitations.',
    logic: 'local source files merged into parent program on compile; cannot be run standalone',
    hint: 'Used to store declarations, subroutines, or screen flow separately.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'standalone'
  },
  {
    id: 'abap-074',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is FORM routine?',
    description: 'Define subroutines (FORM/ENDFORM) in ABAP.',
    logic: 'subroutine block executing local logic, defined by FORM and ended by ENDFORM',
    hint: 'Local subroutines called using the PERFORM statement.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'ENDFORM'
  },
  {
    id: 'abap-075',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference: FORM vs FUNCTION MODULE',
    description: 'Contrast FORM routines and Function Modules.',
    logic: 'FORM is local to program; Function Module is global, testable, and reusable system-wide',
    hint: 'Function modules are stored in a central repository and have import/export parameters.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'global'
  },
  {
    id: 'abap-076',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is PERFORM statement?',
    description: 'Explain PERFORM statement usage.',
    logic: 'statement to execute a local FORM routine subroutine',
    hint: 'Use PERFORM routine_name USING inputs CHANGING outputs.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'subroutine'
  },
  {
    id: 'abap-077',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are function modules?',
    description: 'Explain Function Modules (SE37) and Function Groups.',
    logic: 'global procedures defined in Function Groups, exposing defined interfaces in SE37',
    hint: 'Groups related function modules; can have screen layouts and local memory.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'procedures'
  },
  {
    id: 'abap-078',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of function modules',
    description: 'Identify the three types of Function Modules in SAP.',
    logic: 'Normal Function Module, Remote-Enabled (RFC), Update Function Module',
    hint: 'Normal, RFC, and Update.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Update'
  },
  {
    id: 'abap-079',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is RFC?',
    description: 'Define Remote Function Call (RFC).',
    logic: 'Remote-Enabled Function Module allowing communication between different SAP or non-SAP systems',
    hint: 'Exposed to be called remotely via RFC destinations (SM59).',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Remote'
  },
  {
    id: 'abap-080',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are methods in ABAP OOP?',
    description: 'Explain method definitions and implementations inside classes.',
    logic: 'procedures defined within classes, representing actions an object can execute',
    hint: 'Defined in definition (METHODS) and implemented in class IMPLEMENTATION.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'classes'
  },
  {
    id: 'abap-081',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'SELECT SINGLE vs UP TO 1 ROWS',
    description: 'Contrast SELECT SINGLE and SELECT ... UP TO 1 ROWS in terms of performance and index matching.',
    logic: 'SELECT SINGLE requires primary key fields for performance; UP TO 1 ROWS works without full key',
    hint: 'SELECT SINGLE is optimized for full primary key searches; UP TO 1 ROWS uses ORDER BY.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'primary key'
  },
  {
    id: 'abap-082',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'DELETE vs CLEAR in internal tables',
    description: 'Differentiate DELETE and CLEAR in table memory manipulation.',
    logic: 'DELETE removes table lines; CLEAR clears variables/work area or empties rows but keeps memory allocated',
    hint: 'DELETE physically removes rows (indices shift). CLEAR resets row structure values.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'removes'
  },
  {
    id: 'abap-083',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'MODIFY vs UPDATE database statement',
    description: 'Differentiate database MODIFY and UPDATE behavior.',
    logic: 'UPDATE edits existing DB records; MODIFY inserts if new, else updates',
    hint: 'MODIFY acts as an upsert in the database.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'upsert'
  },
  {
    id: 'abap-084',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Open SQL vs Native SQL',
    description: 'Differentiate Open SQL and Native SQL in database communication.',
    logic: 'Open SQL is database-independent syntax parsed by SAP; Native SQL is database-specific parsed directly by database engine',
    hint: 'Native SQL is surrounded by EXEC SQL ... ENDEXEC.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'independent'
  },
  {
    id: 'abap-085',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is FOR ALL ENTRIES?',
    description: 'Explain FOR ALL ENTRIES syntax and pre-conditions.',
    logic: 'joins an internal table with database tables. Prerequisite: check if internal table is not initial',
    hint: 'Always check IF lt_table IS NOT INITIAL before calling.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'not initial'
  },
  {
    id: 'abap-086',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Find highest salary SQL',
    description: 'Write Open SQL query to find highest salary from employee table ZEMP.',
    logic: 'SELECT MAX( salary ) FROM zemp INTO @lv_max.',
    hint: 'Use MAX aggregate function.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'MAX'
  },
  {
    id: 'abap-087',
    category: 'ABAP',
    difficulty: 'Hard',
    title: 'Find second highest salary SQL',
    description: 'Write Open SQL query logic to find second highest salary.',
    logic: 'SELECT MAX( salary ) FROM zemp WHERE salary < ( SELECT MAX( salary ) FROM zemp ) INTO @lv_second.',
    hint: 'Use a subquery selecting the highest salary, then select the max salary smaller than it.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'subquery'
  },
  {
    id: 'abap-088',
    category: 'ABAP',
    difficulty: 'Hard',
    title: 'Find third highest salary SQL',
    description: 'Explain how to find the third highest salary using subqueries or offset.',
    logic: 'select distinct salary from employee order by salary desc limit 1 offset 2',
    hint: 'Can use nested subqueries or ORDER BY with OFFSET in modern ABAP SQL.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'OFFSET'
  },
  {
    id: 'abap-089',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Find lowest salary SQL',
    description: 'Write Open SQL to find the lowest salary.',
    logic: 'SELECT MIN( salary ) FROM zemp INTO @lv_min.',
    hint: 'Use the MIN aggregate function.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'MIN'
  },
  {
    id: 'abap-090',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Count employees department-wise SQL',
    description: 'Count employees department-wise from ZEMP table.',
    logic: 'SELECT dept, COUNT( * ) FROM zemp GROUP BY dept INTO TABLE @lt_count.',
    hint: 'Use GROUP BY on the department field along with COUNT().',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'GROUP BY'
  },
  {
    id: 'abap-091',
    category: 'ABAP',
    difficulty: 'Hard',
    title: 'Find duplicate records SQL',
    description: 'Write SQL logic to identify duplicate records in table ZEMP based on key field MATNR.',
    logic: 'SELECT matnr, COUNT( * ) FROM zemp GROUP BY matnr HAVING COUNT( * ) > 1 INTO TABLE @lt_dupes.',
    hint: 'GROUP BY matnr and filter using HAVING count > 1.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'HAVING'
  },
  {
    id: 'abap-092',
    category: 'ABAP',
    difficulty: 'Hard',
    title: 'Find employees with salary > average salary',
    description: 'Write Open SQL to select employees earning more than average salary.',
    logic: 'SELECT emp_id FROM zemp WHERE salary > ( SELECT AVG( salary ) FROM zemp ) INTO TABLE @lt_emp.',
    hint: 'Use subquery for average calculation inside WHERE clause.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'subquery'
  },
  {
    id: 'abap-093',
    category: 'ABAP',
    difficulty: 'Hard',
    title: 'Get top 3 salaries SQL',
    description: 'Select top 3 salaries from employee table in modern ABAP.',
    logic: 'SELECT distinct salary FROM zemp ORDER BY salary DESC UP TO 3 ROWS INTO TABLE @lt_top.',
    hint: 'Use ORDER BY DESC and UP TO 3 ROWS (or LIMIT 3).',
    xpFirstSolve: 30, xpRepeatSolve: 6,
    correctAnswer: 'UP TO 3 ROWS'
  },
  {
    id: 'abap-094',
    category: 'ABAP',
    difficulty: 'Hard',
    title: 'Find employees not in another table',
    description: 'Select employees who do not exist in another table ZEMP_TERM.',
    logic: 'SELECT emp_id FROM zemp WHERE emp_id NOT IN ( SELECT emp_id FROM zemp_term )',
    hint: 'Use a subquery with NOT IN, or a LEFT JOIN checking for NULL keys.',
    xpFirstSolve: 35, xpRepeatSolve: 7,
    correctAnswer: 'subquery'
  },
  {
    id: 'abap-095',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'INNER JOIN vs LEFT JOIN',
    description: 'Contrast INNER JOIN and LEFT OUTER JOIN.',
    logic: 'INNER JOIN returns only matching rows; LEFT JOIN returns all rows from left table and matching rows from right',
    hint: 'LEFT JOIN yields null columns for non-matching rows on the right table.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'matching'
  },
  {
    id: 'abap-096',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'JOIN vs FOR ALL ENTRIES',
    description: 'Compare database JOINs with ABAP FOR ALL ENTRIES in terms of performance and network overhead.',
    logic: 'JOIN executes fully on DB layer; FOR ALL ENTRIES executes separate selects or mapped structures using application layer table',
    hint: 'JOIN is generally faster because it minimizes communication rounds between DB and App server.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'DB layer'
  },
  {
    id: 'abap-097',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'GROUP BY and HAVING',
    description: 'Explain GROUP BY and HAVING clauses in Open SQL.',
    logic: 'GROUP BY groups rows by columns; HAVING filters aggregated groups (like WHERE but for aggregates)',
    hint: 'HAVING operates on aggregate results (e.g. SUM, COUNT).',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'aggregate'
  },
  {
    id: 'abap-098',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What are aggregate functions?',
    description: 'List the aggregate functions available in Open SQL.',
    logic: 'MAX, MIN, AVG, SUM, COUNT',
    hint: 'Functions that operate on a set of values to return a single value.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'COUNT'
  },
  {
    id: 'abap-099',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is subquery?',
    description: 'Explain subqueries and where they can be placed in Open SQL.',
    logic: 'a query nested inside another SELECT statement (WHERE or FROM clauses)',
    hint: 'Query inside a query.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'nested'
  },
  {
    id: 'abap-100',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'WHERE vs HAVING',
    description: 'Differentiate between WHERE and HAVING in filtering records.',
    logic: 'WHERE filters individual source rows; HAVING filters grouped aggregate outcomes',
    hint: 'WHERE runs before grouping; HAVING runs after grouping.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'grouping'
  },
  {
    id: 'abap-101',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is ALV report?',
    description: 'Describe ALV reports and user interactive capacity.',
    logic: 'grid data representation allowing standard manipulations (CL_SALV_TABLE or REUSE_ALV_GRID_DISPLAY)',
    hint: 'Provides visual grid format with built-in export and totals.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'grid'
  },
  {
    id: 'abap-102',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Types of ALV display',
    description: 'Identify ALV display objects/APIs.',
    logic: 'Function module (REUSE_ALV), Grid Control (CL_GUI_ALV_GRID), Object Model (CL_SALV_TABLE)',
    hint: 'CL_SALV_TABLE is the modern object-oriented ALV wrapper.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'CL_SALV_TABLE'
  },
  {
    id: 'abap-103',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'REUSE ALV vs OO ALV',
    description: 'Compare REUSE ALV function modules and Object-Oriented ALV grid classes.',
    logic: 'REUSE ALV is functional; OO ALV (CL_GUI_ALV_GRID) uses objects, containers, and event handlers',
    hint: 'OO ALV requires custom containers on screens for drawing the grid.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'container'
  },
  {
    id: 'abap-104',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is field catalog?',
    description: 'Explain what a field catalog (FIELDCAT) represents in ALV generation.',
    logic: 'internal table describing properties (labels, visibility, edit status) of columns in ALV',
    hint: 'Meta-definition table passing column attributes to the ALV engine.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'columns'
  },
  {
    id: 'abap-105',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is layout in ALV?',
    description: 'Explain the layout structure (LVC_S_LAYO / IS_LAYOUT) in ALV formatting.',
    logic: 'structure configuring attributes of the grid as a whole (zebra pattern, edit mode, grid lines)',
    hint: 'Settings that affect the entire grid, not just specific columns.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'grid'
  },
  {
    id: 'abap-106',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'How to enable sorting in ALV?',
    description: 'Explain how to sort columns in ALV programmatically.',
    logic: 'pass sort conditions table (LVC_T_SORT) to grid display parameters',
    hint: 'Fill sort table with fieldname and UP/DOWN flags.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'sort'
  },
  {
    id: 'abap-107',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'How to enable filtering in ALV?',
    description: 'Explain how to set initial column filters in ALV.',
    logic: 'pass filter conditions table (LVC_T_FILT) to grid parameters',
    hint: 'Uses filter structures containing fieldname and filter value.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'filter'
  },
  {
    id: 'abap-108',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are ALV events?',
    description: 'Identify events that can be handled in ALV (hotspot click, double click).',
    logic: 'double_click, hotspot_click, user_command, top_of_page',
    hint: 'Events captured by registering listener classes or passing callback subroutines.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'double_click'
  },
  {
    id: 'abap-109',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is hotspot in ALV?',
    description: 'Define hotspots in ALV columns.',
    logic: 'column style displaying values as underlined links that fire click events',
    hint: 'Looks like a hyperlink. Fires a click event immediately when clicked.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'link'
  },
  {
    id: 'abap-110',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'Advantages of ALV over classical reports',
    description: 'Summarize ALV benefits.',
    logic: 'built-in sorting, filtering, layouts saving, XLS export, zero code grid adjustments',
    hint: 'No need to code manual pagination or search subroutines.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'filtering'
  },
  {
    id: 'abap-111',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is BAPI?',
    description: 'Explain Business Application Programming Interface (BAPI).',
    logic: 'RFC-enabled function module exposing SAP business object methods in the BOR',
    hint: 'Standardized interfaces used to connect external systems with SAP business objects.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'Business Object'
  },
  {
    id: 'abap-112',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference: BAPI vs RFC',
    description: 'Differentiate between BAPI and general RFC function modules.',
    logic: 'BAPI is standard business object method in BOR; RFC is just remote execution capability of any function module',
    hint: 'All BAPIs are RFC-enabled, but not all RFC function modules are BAPIs.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'BOR'
  },
  {
    id: 'abap-113',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference: BAPI vs Function Module',
    description: 'Contrast BAPIs and standard local Function Modules.',
    logic: 'BAPI has strict interface rules, no exceptions, and returns errors in RETURN structure; FM raises exceptions',
    hint: 'BAPIs never raise exceptions programmatically; they populate a RETURN table.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'RETURN'
  },
  {
    id: 'abap-114',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is BAPI_TRANSACTION_COMMIT?',
    description: 'Explain why BAPI_TRANSACTION_COMMIT is required after database writes.',
    logic: 'commits database updates made by BAPIs and releases locks safely',
    hint: 'Needed because BAPIs write to databases but defer the COMMIT statement to the caller.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'commit'
  },
  {
    id: 'abap-115',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is BOR?',
    description: 'Define Business Object Repository (BOR) in SAP.',
    logic: 'central catalog defining SAP business object structures and interfaces (transaction SWO1)',
    hint: 'Expose business models like Employee, SalesOrder as objects with methods.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'SWO1'
  },
  {
    id: 'abap-116',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are standard BAPIs?',
    description: 'Provide examples of standard BAPIs in SAP systems.',
    logic: 'BAPI_SALESORDER_CREATEFROMDAT2, BAPI_USER_CREATE, BAPI_PO_CREATE1',
    hint: 'Common APIs for creating Sales Orders, Purchase Orders, or Users.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'PO_CREATE'
  },
  {
    id: 'abap-117',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'How to find a BAPI?',
    description: 'Which transactions or tools are used to browse BAPIs in SAP?',
    logic: 'use BAPI Explorer (T-code BAPI) or Business Object Builder (SWO1)',
    hint: 'The T-code matches the name of the object: BAPI.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'BAPI'
  },
  {
    id: 'abap-118',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is interface in SAP?',
    description: 'Explain the concept of interfaces in ABAP OOP.',
    logic: 'independent structures defining protocols (method signatures) that classes must implement',
    hint: 'Allows polymorphic calls using interface reference variables.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'classes'
  },
  {
    id: 'abap-119',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What are IDocs?',
    description: 'Explain Intermediate Documents (IDocs) and EDI communication.',
    logic: 'data containers used to exchange business information between SAP and other systems asynchronously',
    hint: 'Consists of Control record, Data records, and Status records.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'containers'
  },
  {
    id: 'abap-120',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Synchronous vs Asynchronous communication',
    description: 'Differentiate Synchronous and Asynchronous interfaces.',
    logic: 'Synchronous waits for execution response immediately; Asynchronous posts message and returns immediately',
    hint: 'IDocs are asynchronous; standard BAPI RFC calls are synchronous.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'asynchronously'
  },
  {
    id: 'abap-121',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is debugging?',
    description: 'Explain debugging in ABAP.',
    logic: 'running programs step-by-step to inspect variable states and execution path',
    hint: 'Launched by entering "/h" command before running program or screen.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'step-by-step'
  },
  {
    id: 'abap-122',
    category: 'ABAP',
    difficulty: 'Easy',
    title: 'What is breakpoint?',
    description: 'Explain breakpoints and contrast Static vs Dynamic breakpoints.',
    logic: 'pause execution at specific statement; static is hardcoded (BREAK-POINT), dynamic set in editor',
    hint: 'Dynamic breakpoints are set on-the-fly and don\'t modify source code.',
    xpFirstSolve: 15, xpRepeatSolve: 3,
    correctAnswer: 'pause'
  },
  {
    id: 'abap-123',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is watchpoint?',
    description: 'Define watchpoints in ABAP debugger.',
    logic: 'conditional break that stops execution when specific variable value changes',
    hint: 'Breaks execution only when the watched variable\'s content changes.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'changes'
  },
  {
    id: 'abap-124',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is user exit?',
    description: 'Define user exits in older SD modules.',
    logic: 'custom subroutines (forms) within standard SAP programs (MV45A) starting with USEREXIT_',
    hint: 'Written in form routines, typically SD modules.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'subroutines'
  },
  {
    id: 'abap-125',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is customer exit?',
    description: 'Define customer exits and T-codes SMOD/CMOD.',
    logic: 'function module exits provided by SAP, managed via transactions SMOD and CMOD',
    hint: 'Identified by prefix EXIT_ followed by program name.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'CMOD'
  },
  {
    id: 'abap-126',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is BADI?',
    description: 'Explain Business Add-Ins (BADI).',
    logic: 'object-oriented enhancement technology based on ABAP interfaces',
    hint: 'Accessed via SE18/SE19. Uses GET BADI and CALL BADI.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'interfaces'
  },
  {
    id: 'abap-127',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'Difference between user exit and BADI',
    description: 'Contrast subroutines (user exits) with Object-Oriented interfaces (BADI).',
    logic: 'User exit is form routine; BADI is class-based interface supporting multiple implementations',
    hint: 'BADIs are object-oriented and support filter-dependency and inheritance.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'class-based'
  },
  {
    id: 'abap-128',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is enhancement framework?',
    description: 'Explain source code enhancements and BAdIs in NetWeaver.',
    logic: 'modern container framework merging customer exits, BADIs, and explicit/implicit enhancements',
    hint: 'Allows inserting custom code at predefined points (implicit/explicit) without modifying standard.',
    xpFirstSolve: 25, xpRepeatSolve: 5,
    correctAnswer: 'implicit'
  },
  {
    id: 'abap-129',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is CMOD?',
    description: 'Explain transaction CMOD purpose.',
    logic: 'Project Management of SAP Enhancements (groups customer exits to activate them)',
    hint: 'Projects are created in CMOD to link and activate SMOD components.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'Projects'
  },
  {
    id: 'abap-130',
    category: 'ABAP',
    difficulty: 'Medium',
    title: 'What is SMOD?',
    description: 'Explain transaction SMOD purpose.',
    logic: 'SAP Enhancement Definitions catalog',
    hint: 'Used to view customer exit components defined by SAP.',
    xpFirstSolve: 20, xpRepeatSolve: 4,
    correctAnswer: 'SMOD'
  }
];
